raptor_dbw_interface:
  ros__parameters:
    steering_ratio: 1.0  # steering wheel angle(deg) / tier angle(rad)
    max_decel     : 5.0  # m/s^2
    max_accel     : 2.0  # m/s^2
    max_jerk      : 1.0  # m/s^3